baseurl = "https://eddyshomepages.github.io/"
title = "Eddy's Homepages"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10


[markup.highlight]
style = "github-dark"

[params]
  author = "Esa P"
  license = '<a rel="license" href="https://mit-license.org/">The MIT License (MIT)</a>'
  info = "I am a passionate enthusiast of Linux and home automation systems. Read and discover more from my blog posts. Olen intohimoinen Linuxin ja kotiautomaatiojärjestelmien harrastaja. Tutustu ja lue lisää blogi-kirjoituksistani."
  description = "Eddy's Homepages"
  keywords = "blog,developer,personal,homeautomation,kotiautomaatio,homeassistant,powerconsumption,energiankulutus,nordpool,zigbee,z-wavw,zwave,mqtt,zigbee2mqtt,zwavejstomqtt"
  avatarurl = "images/omakuva.webp"
  dateFormat = "2.1.2006"
  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"
  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false
  
  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  [params.shareButtons]
    size = "small"
    icon = "solidcircle"
    buttonMargin = "0.1em"
    networks = ["facebook", "twitter", "linkedin", "whatsapp", "email", "telegram", "pinterest"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/eddyshomepages/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://fi.linkedin.com/in/esaporttila/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 5
  url = "https://twitter.com/esa_porttila/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 4
  url = "https://mastodo.fi/@esa_p/"
[[params.social]]
  name = "Facebook"
  icon = "fa fa-facebook fa-2x"
  weight = 1
  url = "https://facebook.com/esa.porttila/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 6
  url = "https://t.me/esa_p/"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 7
  url = "mailto:pikaeetu72@gmail.com"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 8
  url = "/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "Info"
  weight = 1
  url  = "info"
[[menu.main]]
  name = "Posts"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Abouts"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "Tags"
  weight = 4
  url = "tags"
